// Mock CRM data for the Employee / District Executive portal.
// All dates use display-only labels + boolean flags (dueToday / isToday)
// instead of real Date parsing, to avoid SSR/client hydration mismatches.

export const LEAD_STATUSES = [
  "New",
  "Contacted",
  "Interested",
  "Site Visit Scheduled",
  "Site Visit Done",
  "Negotiation",
  "Booked",
  "Lost",
];

export const LEAD_PRIORITIES = ["High", "Medium", "Low"];

export const EMPLOYEE_STATS = {
  totalAssignedLeads: 10,
  newLeads: 2,
  followUpsDueToday: 3,
  siteVisitsScheduled: 2,
  siteVisitsCompleted: 3,
  interestedCustomers: 4,
  bookings: 1,
  pendingFollowUps: 5,
  monthSalesValue: "₹18.5 L",
};

export const EMPLOYEE_LEADS = [
  {
    id: "LD-EMP-3011",
    name: "Mohammed Rafi",
    phone: "+91 98450 11223",
    property: "Luxury 3 BHK Apartment, Indiranagar",
    propertyId: "buy-1",
    district: "Bangalore",
    source: "Website",
    date: "Aug 12, 2026",
    status: "Site Visit Scheduled",
    priority: "High",
    lastFollowUp: "Yesterday",
    nextFollowUp: "Today, 11:00 AM",
    dueToday: true,
    notes: ["Prefers ready-to-move units, wants a north-facing unit."],
  },
  {
    id: "LD-EMP-3012",
    name: "Ahmed Sheikh",
    phone: "+91 90080 22334",
    property: "3 BHK Villa in Devanahalli",
    propertyId: "buy-2",
    district: "Bangalore",
    source: "Referral",
    date: "Aug 20, 2026",
    status: "Interested",
    priority: "High",
    lastFollowUp: "Yesterday",
    nextFollowUp: "Today, 4:00 PM",
    dueToday: true,
    notes: ["Comparing with two other villa projects."],
  },
  {
    id: "LD-EMP-3013",
    name: "Salman Qureshi",
    phone: "+91 99001 33445",
    property: "2 BHK Fully Furnished Flat, Koramangala",
    propertyId: "rent-1",
    district: "Bangalore",
    source: "Walk-in",
    date: "3 days ago",
    status: "Negotiation",
    priority: "Medium",
    lastFollowUp: "3 days ago",
    nextFollowUp: "Today, 6:00 PM",
    dueToday: true,
    notes: ["Negotiating on security deposit terms."],
  },
  {
    id: "LD-EMP-3014",
    name: "Priya Reddy",
    phone: "+91 96204 44556",
    property: "3 BHK Penthouse with Terrace, Indiranagar",
    propertyId: "sell-1",
    district: "Bangalore",
    source: "Website",
    date: "Aug 22, 2026",
    status: "Contacted",
    priority: "Medium",
    lastFollowUp: "2 days ago",
    nextFollowUp: "Tomorrow, 10:00 AM",
    dueToday: false,
    notes: [],
  },
  {
    id: "LD-EMP-3015",
    name: "Kavya Nair",
    phone: "+91 97401 55667",
    property: "Managed Rental Apartment, Whitefield",
    propertyId: "invest-3",
    district: "Bangalore",
    source: "Instagram",
    date: "Aug 18, 2026",
    status: "New",
    priority: "Medium",
    lastFollowUp: "—",
    nextFollowUp: "Tomorrow, 2:00 PM",
    dueToday: false,
    notes: [],
  },
  {
    id: "LD-EMP-3016",
    name: "Ravi Kumar",
    phone: "+91 90352 66778",
    property: "Manufacturing Shed with Power Backup, Peenya",
    propertyId: "industrial-2",
    district: "Bangalore",
    source: "Referral",
    date: "Aug 10, 2026",
    status: "Site Visit Done",
    priority: "Low",
    lastFollowUp: "Today",
    nextFollowUp: "In 3 days",
    dueToday: false,
    notes: ["Visited site on Aug 24, positive feedback on power backup."],
  },
  {
    id: "LD-EMP-3017",
    name: "Fatima Sheikh",
    phone: "+91 98862 77889",
    property: "Luxury 3 BHK Apartment, Indiranagar",
    propertyId: "buy-1",
    district: "Bangalore",
    source: "Website",
    date: "Aug 5, 2026",
    status: "Booked",
    priority: "High",
    lastFollowUp: "5 days ago",
    nextFollowUp: "—",
    dueToday: false,
    notes: ["Booking amount received, documentation in progress."],
  },
  {
    id: "LD-EMP-3018",
    name: "Naveen Gowda",
    phone: "+91 95911 88990",
    property: "3 BHK Villa in Devanahalli",
    propertyId: "buy-2",
    district: "Bangalore",
    source: "Walk-in",
    date: "Aug 2, 2026",
    status: "Lost",
    priority: "Low",
    lastFollowUp: "10 days ago",
    nextFollowUp: "—",
    dueToday: false,
    notes: ["Budget mismatch, went with a competitor project."],
  },
  {
    id: "LD-EMP-3019",
    name: "Divya Shetty",
    phone: "+91 99453 99001",
    property: "2 BHK Fully Furnished Flat, Koramangala",
    propertyId: "rent-1",
    district: "Bangalore",
    source: "Website",
    date: "Aug 21, 2026",
    status: "New",
    priority: "Medium",
    lastFollowUp: "—",
    nextFollowUp: "In 2 days",
    dueToday: false,
    notes: [],
  },
  {
    id: "LD-EMP-3020",
    name: "Arjun Bhat",
    phone: "+91 90080 99112",
    property: "Managed Rental Apartment, Whitefield",
    propertyId: "invest-3",
    district: "Bangalore",
    source: "Referral",
    date: "Aug 15, 2026",
    status: "Contacted",
    priority: "High",
    lastFollowUp: "1 day ago",
    nextFollowUp: "In 4 days",
    dueToday: false,
    notes: [],
  },
];

export const SITE_VISITS = [
  {
    id: "SV-EMP-501",
    leadId: "LD-EMP-3011",
    customer: "Mohammed Rafi",
    property: "Luxury 3 BHK Apartment, Indiranagar",
    time: "11:00 AM",
    sortMinutes: 660,
    isToday: true,
    status: "Scheduled",
    attended: null,
    feedback: "",
    nextAction: "",
  },
  {
    id: "SV-EMP-502",
    leadId: "LD-EMP-3021",
    customer: "Zoya Ahmed",
    property: "2 BHK Fully Furnished Flat, Koramangala",
    time: "2:30 PM",
    sortMinutes: 870,
    isToday: true,
    status: "Scheduled",
    attended: null,
    feedback: "",
    nextAction: "",
  },
  {
    id: "SV-EMP-503",
    leadId: "LD-EMP-3016",
    customer: "Ravi Kumar",
    property: "Manufacturing Shed with Power Backup, Peenya",
    time: "5:00 PM",
    sortMinutes: 1020,
    isToday: false,
    status: "Done",
    attended: true,
    feedback: "Positive feedback on power backup and access road.",
    nextAction: "Send commercial proposal by Friday",
  },
];

export const SALES_TARGET = {
  monthlyTarget: 5000000,
  monthlyTargetLabel: "₹50 Lakh",
  achieved: 1850000,
  achievedLabel: "₹18.5 Lakh",
  totalBookings: 3,
  pendingBookings: 2,
  bookingAmount: "₹6.2 Lakh",
  saleValue: "₹18.5 Lakh",
  commission: "₹92,500",
};

export const PERFORMANCE = {
  month: "August 2026",
  leads: 10,
  contacted: 7,
  siteVisits: 3,
  completedVisits: 1,
  negotiations: 1,
  bookings: 1,
  salesValue: "₹18.5 L",
  conversionRate: "10.0%",
};

export const TERRITORY = {
  district: "Bangalore",
  cities: ["Indiranagar", "Koramangala", "Whitefield", "Devanahalli", "Peenya"],
  projects: ["Simnani Green Residences"],
};

// PROPERTIES[].location is formatted "Area, City" — match the trailing city
// against the employee's assigned district to scope territory inventory.
export function getPropertiesByDistrict(properties, district) {
  if (!district) return [];
  return properties.filter((property) => property.location.includes(district));
}
