"use client";

import { MdRefresh, MdSupervisorAccount } from "react-icons/md";
import CPTypeWorkspace from "@/components/admin/freelancer-cp/CPTypeWorkspace";
import PendingCompanyCpInvites from "@/components/admin/freelancer-cp/PendingCompanyCpInvites";

export default function HeadCPPage() {
  return (
    <>
    <CPTypeWorkspace
      routingStage="head-cp"
      title="Head CP Management"
      description="Every new lead — however it originates — lands here first. Verify it, then forward it to a Company CP; leads never skip straight to Digital or Field CP."
      icon={MdSupervisorAccount}
      accentClasses="border-amber-200 bg-amber-50 text-amber-700"
      showNetworkTab={false}
      showAddPartner={false}
      showInvitationCodes={false}
      showCampaignVideos={false}
      showCommissions={false}
      showAllLeads
      hideRefresh
      hideKpis
      emptyMessage="No leads yet — leads generated by a Digital CP's campaign or a Field CP's direct lead will show up here first, before anywhere else."
    />
    <div className="mb-4 flex justify-end">
      <button
        type="button"
        onClick={() => window.location.reload()}
        className="flex h-9 items-center gap-1.5 rounded-xl border border-[#1a1a2e] bg-[#1a1a2e] px-3.5 text-xs font-semibold text-white shadow-sm transition hover:bg-[#2d334d] hover:border-[#2d334d]"
      >
        <MdRefresh size={16} className="text-[#f0b429]" />
        <span>Refresh</span>
      </button>
    </div>
    <PendingCompanyCpInvites />
    </>
  );
}
