"use client";

import { MdSupervisorAccount } from "react-icons/md";
import CPTypeWorkspace from "@/components/admin/freelancer-cp/CPTypeWorkspace";

export default function HeadCPPage() {
  return (
    <CPTypeWorkspace
      routingStage="head-cp"
      title="Head CP Management"
      description="Every new lead — however it originates — lands here first. Verify it, then forward it to a Company CP; leads never skip straight to Digital or Field CP."
      icon={MdSupervisorAccount}
      accentClasses="border-amber-200 bg-amber-50 text-amber-700"
      showNetworkTab={false}
      showAddPartner={false}
      showInvitationCodes={false}
      showCampaignVideos={false}
      showCommissions={false}
      emptyMessage="No leads pending — leads generated by a Digital CP's campaign or a Field CP's direct lead will show up here first, before anywhere else."
    />
  );
}
